<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'phone_code' => '+93', 'phone_number_limit' => 9],
            ['name' => 'Åland Islands', 'code' => 'AX', 'phone_code' => '+358', 'phone_number_limit' => 10],
            ['name' => 'Albania', 'code' => 'AL', 'phone_code' => '+355', 'phone_number_limit' => 9],
            ['name' => 'Algeria', 'code' => 'DZ', 'phone_code' => '+213', 'phone_number_limit' => 9],
            ['name' => 'American Samoa', 'code' => 'AS', 'phone_code' => '+1684', 'phone_number_limit' => 7],
            ['name' => 'Andorra', 'code' => 'AD', 'phone_code' => '+376', 'phone_number_limit' => 9],
            ['name' => 'Angola', 'code' => 'AO', 'phone_code' => '+244', 'phone_number_limit' => 9],
            ['name' => 'Anguilla', 'code' => 'AI', 'phone_code' => '+1264', 'phone_number_limit' => 7],
            ['name' => 'Antarctica', 'code' => 'AQ', 'phone_code' => '+672', 'phone_number_limit' => 6],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'phone_code' => '+1268', 'phone_number_limit' => 7],
            ['name' => 'Argentina', 'code' => 'AR', 'phone_code' => '+54', 'phone_number_limit' => 10],
            ['name' => 'Armenia', 'code' => 'AM', 'phone_code' => '+374', 'phone_number_limit' => 8],
            ['name' => 'Aruba', 'code' => 'AW', 'phone_code' => '+297', 'phone_number_limit' => 7],
            ['name' => 'Australia', 'code' => 'AU', 'phone_code' => '+61', 'phone_number_limit' => 9],
            ['name' => 'Austria', 'code' => 'AT', 'phone_code' => '+43', 'phone_number_limit' => 10],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'phone_code' => '+994', 'phone_number_limit' => 9],
            ['name' => 'Bahamas', 'code' => 'BS', 'phone_code' => '+1242', 'phone_number_limit' => 7],
            ['name' => 'Bahrain', 'code' => 'BH', 'phone_code' => '+973', 'phone_number_limit' => 8],
            ['name' => 'Bangladesh', 'code' => 'BD', 'phone_code' => '+880', 'phone_number_limit' => 10],
            ['name' => 'Barbados', 'code' => 'BB', 'phone_code' => '+1246', 'phone_number_limit' => 7],
            ['name' => 'Belarus', 'code' => 'BY', 'phone_code' => '+375', 'phone_number_limit' => 9],
            ['name' => 'Belgium', 'code' => 'BE', 'phone_code' => '+32', 'phone_number_limit' => 9],
            ['name' => 'Belize', 'code' => 'BZ', 'phone_code' => '+501', 'phone_number_limit' => 7],
            ['name' => 'Benin', 'code' => 'BJ', 'phone_code' => '+229', 'phone_number_limit' => 8],
            ['name' => 'Bermuda', 'code' => 'BM', 'phone_code' => '+1441', 'phone_number_limit' => 7],
            ['name' => 'Bhutan', 'code' => 'BT', 'phone_code' => '+975', 'phone_number_limit' => 8],
            ['name' => 'Bolivia, Plurinational State of', 'code' => 'BO', 'phone_code' => '+591', 'phone_number_limit' => 8],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ', 'phone_code' => '+599', 'phone_number_limit' => 7],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'phone_code' => '+387', 'phone_number_limit' => 8],
            ['name' => 'Botswana', 'code' => 'BW', 'phone_code' => '+267', 'phone_number_limit' => 8],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'phone_code' => '+55', 'phone_number_limit' => 10],
            ['name' => 'Brazil', 'code' => 'BR', 'phone_code' => '+55', 'phone_number_limit' => 10],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'phone_code' => '+246', 'phone_number_limit' => 7],
            ['name' => 'Brunei Darussalam', 'code' => 'BN', 'phone_code' => '+673', 'phone_number_limit' => 7],
            ['name' => 'Bulgaria', 'code' => 'BG', 'phone_code' => '+359', 'phone_number_limit' => 9],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'phone_code' => '+226', 'phone_number_limit' => 8],
            ['name' => 'Burundi', 'code' => 'BI', 'phone_code' => '+257', 'phone_number_limit' => 8],
            ['name' => 'Cambodia', 'code' => 'KH', 'phone_code' => '+855', 'phone_number_limit' => 8],
            ['name' => 'Cameroon', 'code' => 'CM', 'phone_code' => '+237', 'phone_number_limit' => 9],
            ['name' => 'Canada', 'code' => 'CA', 'phone_code' => '+1', 'phone_number_limit' => 10],
            ['name' => 'Cape Verde', 'code' => 'CV', 'phone_code' => '+238', 'phone_number_limit' => 7],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'phone_code' => '+1345', 'phone_number_limit' => 7],
            ['name' => 'Central African Republic', 'code' => 'CF', 'phone_code' => '+236', 'phone_number_limit' => 9],
            ['name' => 'Chad', 'code' => 'TD', 'phone_code' => '+235', 'phone_number_limit' => 9],
            ['name' => 'Chile', 'code' => 'CL', 'phone_code' => '+56', 'phone_number_limit' => 9],
            ['name' => 'China', 'code' => 'CN', 'phone_code' => '+86', 'phone_number_limit' => 11],
            ['name' => 'Christmas Island', 'code' => 'CX', 'phone_code' => '+61', 'phone_number_limit' => 9],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'phone_code' => '+61', 'phone_number_limit' => 9],
            ['name' => 'Colombia', 'code' => 'CO', 'phone_code' => '+57', 'phone_number_limit' => 10],
            ['name' => 'Comoros', 'code' => 'KM', 'phone_code' => '+269', 'phone_number_limit' => 7],
            ['name' => 'Congo', 'code' => 'CG', 'phone_code' => '+242', 'phone_number_limit' => 9],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD', 'phone_code' => '+243', 'phone_number_limit' => 9],
            ['name' => 'Cook Islands', 'code' => 'CK', 'phone_code' => '+682', 'phone_number_limit' => 5],
            ['name' => 'Costa Rica', 'code' => 'CR', 'phone_code' => '+506', 'phone_number_limit' => 8],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'phone_code' => '+225', 'phone_number_limit' => 8],
            ['name' => 'Croatia', 'code' => 'HR', 'phone_code' => '+385', 'phone_number_limit' => 9],
            ['name' => 'Cuba', 'code' => 'CU', 'phone_code' => '+53', 'phone_number_limit' => 8],
            ['name' => 'Curaçao', 'code' => 'CW', 'phone_code' => '+599', 'phone_number_limit' => 7],
            ['name' => 'Cyprus', 'code' => 'CY', 'phone_code' => '+357', 'phone_number_limit' => 8],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'phone_code' => '+420', 'phone_number_limit' => 9],
            ['name' => 'Denmark', 'code' => 'DK', 'phone_code' => '+45', 'phone_number_limit' => 8],
            ['name' => 'Djibouti', 'code' => 'DJ', 'phone_code' => '+253', 'phone_number_limit' => 6],
            ['name' => 'Dominica', 'code' => 'DM', 'phone_code' => '+1767', 'phone_number_limit' => 7],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'phone_code' => '+1809', 'phone_number_limit' => 10],
            ['name' => 'Ecuador', 'code' => 'EC', 'phone_code' => '+593', 'phone_number_limit' => 9],
            ['name' => 'Egypt', 'code' => 'EG', 'phone_code' => '+20', 'phone_number_limit' => 10],
            ['name' => 'El Salvador', 'code' => 'SV', 'phone_code' => '+503', 'phone_number_limit' => 8],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'phone_code' => '+240', 'phone_number_limit' => 9],
            ['name' => 'Eritrea', 'code' => 'ER', 'phone_code' => '+291', 'phone_number_limit' => 7],
            ['name' => 'Estonia', 'code' => 'EE', 'phone_code' => '+372', 'phone_number_limit' => 8],
            ['name' => 'Eswatini', 'code' => 'SZ', 'phone_code' => '+268', 'phone_number_limit' => 7],
            ['name' => 'Ethiopia', 'code' => 'ET', 'phone_code' => '+251', 'phone_number_limit' => 9],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'phone_code' => '+500', 'phone_number_limit' => 5],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'phone_code' => '+298', 'phone_number_limit' => 6],
            ['name' => 'Fiji', 'code' => 'FJ', 'phone_code' => '+679', 'phone_number_limit' => 7],
            ['name' => 'Finland', 'code' => 'FI', 'phone_code' => '+358', 'phone_number_limit' => 9],
            ['name' => 'France', 'code' => 'FR', 'phone_code' => '+33', 'phone_number_limit' => 9],
            ['name' => 'French Guiana', 'code' => 'GF', 'phone_code' => '+594', 'phone_number_limit' => 9],
            ['name' => 'French Polynesia', 'code' => 'PF', 'phone_code' => '+689', 'phone_number_limit' => 6],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'phone_code' => '+262', 'phone_number_limit' => 9],
            ['name' => 'Gabon', 'code' => 'GA', 'phone_code' => '+241', 'phone_number_limit' => 9],
            ['name' => 'Gambia', 'code' => 'GM', 'phone_code' => '+220', 'phone_number_limit' => 7],
            ['name' => 'Georgia', 'code' => 'GE', 'phone_code' => '+995', 'phone_number_limit' => 9],
            ['name' => 'Germany', 'code' => 'DE', 'phone_code' => '+49', 'phone_number_limit' => 10],
            ['name' => 'Ghana', 'code' => 'GH', 'phone_code' => '+233', 'phone_number_limit' => 9],
            ['name' => 'Gibraltar', 'code' => 'GI', 'phone_code' => '+350', 'phone_number_limit' => 8],
            ['name' => 'Greece', 'code' => 'GR', 'phone_code' => '+30', 'phone_number_limit' => 10],
            ['name' => 'Greenland', 'code' => 'GL', 'phone_code' => '+299', 'phone_number_limit' => 6],
            ['name' => 'Grenada', 'code' => 'GD', 'phone_code' => '+1473', 'phone_number_limit' => 7],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'phone_code' => '+590', 'phone_number_limit' => 9],
            ['name' => 'Guam', 'code' => 'GU', 'phone_code' => '+1671', 'phone_number_limit' => 7],
            ['name' => 'Guatemala', 'code' => 'GT', 'phone_code' => '+502', 'phone_number_limit' => 8],
            ['name' => 'Guernsey', 'code' => 'GG', 'phone_code' => '+44', 'phone_number_limit' => 10],
            ['name' => 'Guinea', 'code' => 'GN', 'phone_code' => '+224', 'phone_number_limit' => 9],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'phone_code' => '+245', 'phone_number_limit' => 7],
            ['name' => 'Guyana', 'code' => 'GY', 'phone_code' => '+592', 'phone_number_limit' => 7],
            ['name' => 'Haiti', 'code' => 'HT', 'phone_code' => '+509', 'phone_number_limit' => 8],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'HM', 'phone_code' => '+672', 'phone_number_limit' => 6],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'phone_code' => '+39', 'phone_number_limit' => 10],
            ['name' => 'Honduras', 'code' => 'HN', 'phone_code' => '+504', 'phone_number_limit' => 8],
            ['name' => 'Hong Kong', 'code' => 'HK', 'phone_code' => '+852', 'phone_number_limit' => 8],
            ['name' => 'Hungary', 'code' => 'HU', 'phone_code' => '+36', 'phone_number_limit' => 9],
            ['name' => 'Iceland', 'code' => 'IS', 'phone_code' => '+354', 'phone_number_limit' => 7],
            ['name' => 'India', 'code' => 'IN', 'phone_code' => '+91', 'phone_number_limit' => 10],
            ['name' => 'Indonesia', 'code' => 'ID', 'phone_code' => '+62', 'phone_number_limit' => 11],
            ['name' => 'Iran', 'code' => 'IR', 'phone_code' => '+98', 'phone_number_limit' => 10],
            ['name' => 'Iraq', 'code' => 'IQ', 'phone_code' => '+964', 'phone_number_limit' => 10],
            ['name' => 'Ireland', 'code' => 'IE', 'phone_code' => '+353', 'phone_number_limit' => 9],
            ['name' => 'Isle of Man', 'code' => 'IM', 'phone_code' => '+44', 'phone_number_limit' => 10],
            ['name' => 'Israel', 'code' => 'IL', 'phone_code' => '+972', 'phone_number_limit' => 9],
            ['name' => 'Italy', 'code' => 'IT', 'phone_code' => '+39', 'phone_number_limit' => 10],
            ['name' => 'Jamaica', 'code' => 'JM', 'phone_code' => '+1876', 'phone_number_limit' => 7],
            ['name' => 'Japan', 'code' => 'JP', 'phone_code' => '+81', 'phone_number_limit' => 10],
            ['name' => 'Jersey', 'code' => 'JE', 'phone_code' => '+44', 'phone_number_limit' => 10],
            ['name' => 'Jordan', 'code' => 'JO', 'phone_code' => '+962', 'phone_number_limit' => 9],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'phone_code' => '+7', 'phone_number_limit' => 10],
            ['name' => 'Kenya', 'code' => 'KE', 'phone_code' => '+254', 'phone_number_limit' => 9],
            ['name' => 'Kiribati', 'code' => 'KI', 'phone_code' => '+686', 'phone_number_limit' => 8],
            ['name' => 'North Korea', 'code' => 'KP', 'phone_code' => '+850', 'phone_number_limit' => 9],
            ['name' => 'South Korea', 'code' => 'KR', 'phone_code' => '+82', 'phone_number_limit' => 9],
            ['name' => 'Kuwait', 'code' => 'KW', 'phone_code' => '+965', 'phone_number_limit' => 8],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'phone_code' => '+996', 'phone_number_limit' => 9],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'phone_code' => '+856', 'phone_number_limit' => 9],
            ['name' => 'Latvia', 'code' => 'LV', 'phone_code' => '+371', 'phone_number_limit' => 8],
            ['name' => 'Lebanon', 'code' => 'LB', 'phone_code' => '+961', 'phone_number_limit' => 8],
            ['name' => 'Lesotho', 'code' => 'LS', 'phone_code' => '+266', 'phone_number_limit' => 8],
            ['name' => 'Liberia', 'code' => 'LR', 'phone_code' => '+231', 'phone_number_limit' => 7],
            ['name' => 'Libya', 'code' => 'LY', 'phone_code' => '+218', 'phone_number_limit' => 9],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'phone_code' => '+423', 'phone_number_limit' => 9],
            ['name' => 'Lithuania', 'code' => 'LT', 'phone_code' => '+370', 'phone_number_limit' => 8],
            ['name' => 'Luxembourg', 'code' => 'LU', 'phone_code' => '+352', 'phone_number_limit' => 9],
            ['name' => 'Macao', 'code' => 'MO', 'phone_code' => '+853', 'phone_number_limit' => 8],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MK', 'phone_code' => '+389', 'phone_number_limit' => 8],
            ['name' => 'Madagascar', 'code' => 'MG', 'phone_code' => '+261', 'phone_number_limit' => 9],
            ['name' => 'Malawi', 'code' => 'MW', 'phone_code' => '+265', 'phone_number_limit' => 9],
            ['name' => 'Malaysia', 'code' => 'MY', 'phone_code' => '+60', 'phone_number_limit' => 10],
            ['name' => 'Maldives', 'code' => 'MV', 'phone_code' => '+960', 'phone_number_limit' => 7],
            ['name' => 'Mali', 'code' => 'ML', 'phone_code' => '+223', 'phone_number_limit' => 8],
            ['name' => 'Malta', 'code' => 'MT', 'phone_code' => '+356', 'phone_number_limit' => 8],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'phone_code' => '+692', 'phone_number_limit' => 7],
            ['name' => 'Martinique', 'code' => 'MQ', 'phone_code' => '+596', 'phone_number_limit' => 9],
            ['name' => 'Mauritania', 'code' => 'MR', 'phone_code' => '+222', 'phone_number_limit' => 8],
            ['name' => 'Mauritius', 'code' => 'MU', 'phone_code' => '+230', 'phone_number_limit' => 8],
            ['name' => 'Mayotte', 'code' => 'YT', 'phone_code' => '+262', 'phone_number_limit' => 9],
            ['name' => 'Mexico', 'code' => 'MX', 'phone_code' => '+52', 'phone_number_limit' => 10],
            ['name' => 'Micronesia', 'code' => 'FM', 'phone_code' => '+691', 'phone_number_limit' => 7],
            ['name' => 'Moldova, Republic of', 'code' => 'MD', 'phone_code' => '+373', 'phone_number_limit' => 8],
            ['name' => 'Monaco', 'code' => 'MC', 'phone_code' => '+377', 'phone_number_limit' => 8],
            ['name' => 'Mongolia', 'code' => 'MN', 'phone_code' => '+976', 'phone_number_limit' => 8],
            ['name' => 'Montenegro', 'code' => 'ME', 'phone_code' => '+382', 'phone_number_limit' => 8],
            ['name' => 'Montserrat', 'code' => 'MS', 'phone_code' => '+1664', 'phone_number_limit' => 7],
            ['name' => 'Morocco', 'code' => 'MA', 'phone_code' => '+212', 'phone_number_limit' => 9],
            ['name' => 'Mozambique', 'code' => 'MZ', 'phone_code' => '+258', 'phone_number_limit' => 9],
            ['name' => 'Myanmar', 'code' => 'MM', 'phone_code' => '+95', 'phone_number_limit' => 8],
            ['name' => 'Namibia', 'code' => 'NA', 'phone_code' => '+264', 'phone_number_limit' => 9],
            ['name' => 'Nauru', 'code' => 'NR', 'phone_code' => '+674', 'phone_number_limit' => 7],
            ['name' => 'Nepal', 'code' => 'NP', 'phone_code' => '+977', 'phone_number_limit' => 10],
            ['name' => 'Netherlands', 'code' => 'NL', 'phone_code' => '+31', 'phone_number_limit' => 9],
            ['name' => 'New Caledonia', 'code' => 'NC', 'phone_code' => '+687', 'phone_number_limit' => 6],
            ['name' => 'New Zealand', 'code' => 'NZ', 'phone_code' => '+64', 'phone_number_limit' => 9],
            ['name' => 'Nicaragua', 'code' => 'NI', 'phone_code' => '+505', 'phone_number_limit' => 8],
            ['name' => 'Niger', 'code' => 'NE', 'phone_code' => '+227', 'phone_number_limit' => 8],
            ['name' => 'Nigeria', 'code' => 'NG', 'phone_code' => '+234', 'phone_number_limit' => 10],
            ['name' => 'Niue', 'code' => 'NU', 'phone_code' => '+683', 'phone_number_limit' => 4],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'phone_code' => '+672', 'phone_number_limit' => 6],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'phone_code' => '+1670', 'phone_number_limit' => 7],
            ['name' => 'Norway', 'code' => 'NO', 'phone_code' => '+47', 'phone_number_limit' => 8],
            ['name' => 'Oman', 'code' => 'OM', 'phone_code' => '+968', 'phone_number_limit' => 8],
            ['name' => 'Pakistan', 'code' => 'PK', 'phone_code' => '+92', 'phone_number_limit' => 10],
            ['name' => 'Palau', 'code' => 'PW', 'phone_code' => '+680', 'phone_number_limit' => 7],
            ['name' => 'Palestine, State of', 'code' => 'PS', 'phone_code' => '+970', 'phone_number_limit' => 9],
            ['name' => 'Panama', 'code' => 'PA', 'phone_code' => '+507', 'phone_number_limit' => 8],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'phone_code' => '+675', 'phone_number_limit' => 7],
            ['name' => 'Paraguay', 'code' => 'PY', 'phone_code' => '+595', 'phone_number_limit' => 9],
            ['name' => 'Peru', 'code' => 'PE', 'phone_code' => '+51', 'phone_number_limit' => 9],
            ['name' => 'Philippines', 'code' => 'PH', 'phone_code' => '+63', 'phone_number_limit' => 10],
            ['name' => 'Pitcairn', 'code' => 'PN', 'phone_code' => '+64', 'phone_number_limit' => 9],
            ['name' => 'Poland', 'code' => 'PL', 'phone_code' => '+48', 'phone_number_limit' => 9],
            ['name' => 'Portugal', 'code' => 'PT', 'phone_code' => '+351', 'phone_number_limit' => 9],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'phone_code' => '+1939', 'phone_number_limit' => 7],
            ['name' => 'Qatar', 'code' => 'QA', 'phone_code' => '+974', 'phone_number_limit' => 8],
            ['name' => 'Réunion', 'code' => 'RE', 'phone_code' => '+262', 'phone_number_limit' => 9],
            ['name' => 'Romania', 'code' => 'RO', 'phone_code' => '+40', 'phone_number_limit' => 9],
            ['name' => 'Russian Federation', 'code' => 'RU', 'phone_code' => '+7', 'phone_number_limit' => 10],
            ['name' => 'Rwanda', 'code' => 'RW', 'phone_code' => '+250', 'phone_number_limit' => 9],
            ['name' => 'Saint Barthélemy', 'code' => 'BL', 'phone_code' => '+590', 'phone_number_limit' => 9],
            ['name' => 'Saint Helena', 'code' => 'SH', 'phone_code' => '+290', 'phone_number_limit' => 4],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'phone_code' => '+1869', 'phone_number_limit' => 7],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'phone_code' => '+1758', 'phone_number_limit' => 7],
            ['name' => 'Saint Martin (French part)', 'code' => 'MF', 'phone_code' => '+590', 'phone_number_limit' => 9],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'phone_code' => '+508', 'phone_number_limit' => 6],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'phone_code' => '+1784', 'phone_number_limit' => 7],
            ['name' => 'Samoa', 'code' => 'WS', 'phone_code' => '+685', 'phone_number_limit' => 6],
            ['name' => 'San Marino', 'code' => 'SM', 'phone_code' => '+378', 'phone_number_limit' => 9],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'phone_code' => '+239', 'phone_number_limit' => 7],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'phone_code' => '+966', 'phone_number_limit' => 9],
            ['name' => 'Senegal', 'code' => 'SN', 'phone_code' => '+221', 'phone_number_limit' => 9],
            ['name' => 'Serbia', 'code' => 'RS', 'phone_code' => '+381', 'phone_number_limit' => 8],
            ['name' => 'Seychelles', 'code' => 'SC', 'phone_code' => '+248', 'phone_number_limit' => 7],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'phone_code' => '+232', 'phone_number_limit' => 8],
            ['name' => 'Singapore', 'code' => 'SG', 'phone_code' => '+65', 'phone_number_limit' => 8],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX', 'phone_code' => '+1721', 'phone_number_limit' => 7],
            ['name' => 'Slovakia', 'code' => 'SK', 'phone_code' => '+421', 'phone_number_limit' => 9],
            ['name' => 'Slovenia', 'code' => 'SI', 'phone_code' => '+386', 'phone_number_limit' => 8],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'phone_code' => '+677', 'phone_number_limit' => 7],
            ['name' => 'Somalia', 'code' => 'SO', 'phone_code' => '+252', 'phone_number_limit' => 7],
            ['name' => 'South Africa', 'code' => 'ZA', 'phone_code' => '+27', 'phone_number_limit' => 9],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'phone_code' => '+500', 'phone_number_limit' => 5],
            ['name' => 'South Sudan', 'code' => 'SS', 'phone_code' => '+211', 'phone_number_limit' => 9],
            ['name' => 'Spain', 'code' => 'ES', 'phone_code' => '+34', 'phone_number_limit' => 9],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'phone_code' => '+94', 'phone_number_limit' => 9],
            ['name' => 'Sudan', 'code' => 'SD', 'phone_code' => '+249', 'phone_number_limit' => 9],
            ['name' => 'Suriname', 'code' => 'SR', 'phone_code' => '+597', 'phone_number_limit' => 6],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'phone_code' => '+47', 'phone_number_limit' => 8],
            ['name' => 'Sweden', 'code' => 'SE', 'phone_code' => '+46', 'phone_number_limit' => 9],
            ['name' => 'Switzerland', 'code' => 'CH', 'phone_code' => '+41', 'phone_number_limit' => 9],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY', 'phone_code' => '+963', 'phone_number_limit' => 9],
            ['name' => 'Taiwan, Province of China', 'code' => 'TW', 'phone_code' => '+886', 'phone_number_limit' => 9],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'phone_code' => '+992', 'phone_number_limit' => 9],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ', 'phone_code' => '+255', 'phone_number_limit' => 9],
            ['name' => 'Thailand', 'code' => 'TH', 'phone_code' => '+66', 'phone_number_limit' => 9],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'phone_code' => '+670', 'phone_number_limit' => 7],
            ['name' => 'Togo', 'code' => 'TG', 'phone_code' => '+228', 'phone_number_limit' => 8],
            ['name' => 'Tokelau', 'code' => 'TK', 'phone_code' => '+690', 'phone_number_limit' => 4],
            ['name' => 'Tonga', 'code' => 'TO', 'phone_code' => '+676', 'phone_number_limit' => 5],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'phone_code' => '+1868', 'phone_number_limit' => 7],
            ['name' => 'Tunisia', 'code' => 'TN', 'phone_code' => '+216', 'phone_number_limit' => 8],
            ['name' => 'Turkey', 'code' => 'TR', 'phone_code' => '+90', 'phone_number_limit' => 10],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'phone_code' => '+993', 'phone_number_limit' => 8],
            ['name' => 'Tuvalu', 'code' => 'TV', 'phone_code' => '+688', 'phone_number_limit' => 5],
            ['name' => 'Uganda', 'code' => 'UG', 'phone_code' => '+256', 'phone_number_limit' => 9],
            ['name' => 'Ukraine', 'code' => 'UA', 'phone_code' => '+380', 'phone_number_limit' => 9],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'phone_code' => '+971', 'phone_number_limit' => 9],
            ['name' => 'United Kingdom', 'code' => 'GB', 'phone_code' => '+44', 'phone_number_limit' => 10],
            ['name' => 'United States', 'code' => 'US', 'phone_code' => '+1', 'phone_number_limit' => 10],
            ['name' => 'Uruguay', 'code' => 'UY', 'phone_code' => '+598', 'phone_number_limit' => 8],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'phone_code' => '+998', 'phone_number_limit' => 9],
            ['name' => 'Vanuatu', 'code' => 'VU', 'phone_code' => '+678', 'phone_number_limit' => 7],
            ['name' => 'Venezuela', 'code' => 'VE', 'phone_code' => '+58', 'phone_number_limit' => 9],
            ['name' => 'Viet Nam', 'code' => 'VN', 'phone_code' => '+84', 'phone_number_limit' => 10],
            ['name' => 'Wallis and Futuna', 'code' => 'WF', 'phone_code' => '+681', 'phone_number_limit' => 6],
            ['name' => 'Western Sahara', 'code' => 'EH', 'phone_code' => '+212', 'phone_number_limit' => 9],
            ['name' => 'Yemen', 'code' => 'YE', 'phone_code' => '+967', 'phone_number_limit' => 9],
            ['name' => 'Zambia', 'code' => 'ZM', 'phone_code' => '+260', 'phone_number_limit' => 9],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'phone_code' => '+263', 'phone_number_limit' => 9]
        ];
        
        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
